spring: 
  application: 
    name: customer-service
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create  
  h2:
    console:
      settings:
        trace: true 
# spring.jpa.defer-datasource-initialization=true      