server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marceltessarini/config-server-properties.git
          searchPaths: 
            - '{application}/{profile}'
            - 'application-{profile}'
          refreshRate: 300
